#!/bin/bash

which ruby
if [ $? = 1 ]; then
  echo "Ruby isn't installed"
  exit 1
fi

# install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install formulas
brew install vim --with-override-system-vi
brew install git
brew cask install iterm2
brew install ag
brew install tree
brew install tmux
brew install gpg
brew install exercism
brew install tmux
brew upgrade gnupg
brew link --overwrite gnupg
brew install node
brew install mysql@5.6
brew install mysql
brew install terraform
brew install mycli
brew install lastpass-cli --with-pinentry
brew install imagemagick --disable-openmp --build-from-source
brew install wget
brew install kubectl
brew tap codeclimate/formulae
brew install codeclimate
brew install fzf
$(brew --prefix)/opt/fzf/install
brew install ansible
brew install noti
brew install postgresql@9.6
brew install sqlite3
brew install percona-toolkit
brew install hub
brew install phantomjs
brew install cask chromedriver
brew install kubernetes-helm
brew install graphviz
brew install bash-completion
brew install elixir
brew install coreutils automake autoconf openssl libyaml readline libxslt libtool unixodbc
brew install git-extras
brew install watch
brew install inetutils
brew install ssh-copy-id
