#!/bin/bash

# Install Platform Specific Packages
platform=`uname`
echo $platform
if [[ $platform == "Darwin" ]]; then
  brew install the_silver_searcher
elif [[ $platform == "Linux" ]]; then
  sudo apt-get install silversearcher-ag vim-gnome
fi

# Install Pathogen
mkdir -p $HOME/.vim/autoload $HOME/.vim/bundle && \
  curl -LSso $HOME/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install Vim Colors
function install_color() {
  url=$1
  folder=`echo "vim-color" | md5`
  git clone $url $folder
  cp -r $folder/colors/* $HOME/.vim/colors/
  rm -rf $folder
}

mkdir -p $HOME/.vim/colors
declare -a repos=(
  "https://github.com/nanotech/jellybeans.vim.git"
  "https://github.com/KeitaNakamura/neodark.vim.git"
)
for repo in "${repos[@]}"; do
  install_color $repo
done

# Install NPM Packages Needed
if [[ $(which npm &>/dev/null) ]]; then
    npm install -g ocaml-language-server
else
    echo "Install NPM, then run"
    echo "\n\tnpm install -g ocaml-language-server\n"
fi

# Install Vim Plugins
declare -a repos=(
  "https://github.com/rking/ag.vim"
  "https://github.com/mileszs/ack.vim.git"
  "https://github.com/slashmili/alchemist.vim.git"
  "https://github.com/w0rp/ale.git"
  "https://github.com/kien/ctrlp.vim.git"
  "https://github.com/tpope/vim-dispatch.git"
  "https://github.com/editorconfig/editorconfig-vim.git"
  "https://github.com/ElmCast/elm-vim.git"
  "https://github.com/mattn/emmet-vim.git"
  "https://github.com/ngmy/vim-rubocop.git"
  "https://github.com/eagletmt/ghcmod-vim.git"
  "https://github.com/eagletmt/neco-ghc.git"
  "https://github.com/Shougo/neocomplete.vim.git"
  "https://github.com/scrooloose/nerdcommenter.git"
  "https://github.com/scrooloose/nerdtree.git"
  "https://github.com/FrigoEU/psc-ide-vim.git"
  "https://github.com/raichoo/purescript-vim.git"
  "https://github.com/ruby-formatter/rufo-vim.git"
  "https://github.com/ervandew/supertab.git"
  "https://github.com/vim-syntastic/syntastic.git"
  "https://github.com/godlygeek/tabular.git"
  "https://github.com/tomtom/tlib_vim.git"
  "https://github.com/mbbill/undotree.git"
  "https://github.com/vim-airline/vim-airline.git"
  "https://github.com/vim-airline/vim-airline-themes.git"
  "https://github.com/MarcWeber/vim-addon-mw-utils.git"
  "https://github.com/tpope/vim-bundler.git"
  "https://github.com/kchmck/vim-coffee-script.git"
  "https://github.com/tpope/vim-commentary.git"
  "https://github.com/easymotion/vim-easymotion.git"
  "https://github.com/elixir-editors/vim-elixir.git"
  "https://github.com/tpope/vim-endwise.git"
  "https://github.com/tpope/vim-fugitive.git"
  "https://github.com/fatih/vim-go.git"
  "https://github.com/tpope/vim-haml.git"
  "https://github.com/pangloss/vim-javascript.git"
  "https://github.com/mxw/vim-jsx.git"
  "https://github.com/yaymukund/vim-rabl.git"
  "https://github.com/reasonml-editor/vim-reason-plus.git"
  "https://github.com/vim-ruby/vim-ruby.git"
  "https://github.com/thoughtbot/vim-rspec.git"
  "https://github.com/tpope/vim-surround.git"
  "https://github.com/hashivim/vim-terraform.git"
  "https://github.com/christoomey/vim-tmux-navigator.git"
  "https://github.com/skalnik/vim-vroom.git"
  "https://github.com/tpope/vim-rails.git"
  "https://github.com/Shougo/vimproc.vim.git"
)

cd $HOME/.vim/bundle
for repo in "${repos[@]}"; do
  git clone $repo
done

vim -u NONE -c "helptags vim-rails/doc" -c q

cd vimproc.vim
make
